### ISSUE TITLE
Shows as being on laptop battery when finished charging

### ISSUE THREAD

**Issue by mspaulding06** [mate-desktop/mate-power-manager#198] opened 2016-07-23 19:27 UTC
When my laptop finishes charging, I see a popup message that says it is discharging on the laptop battery even though my laptop is still plugged in.  It never switches to say that the laptop is on A/C.
![powerdisplay](https://cloud.githubusercontent.com/assets/216318/17079834/bd7dc71c-50d0-11e6-83bc-a834d6bf9fae.png)
##

**Comment by raveit65** [comment] 2016-07-23 19:35
well, i lost my crystal ball last week ;)
and sorry w/o infos like distro, mate version, package version, systemd or not, nobody can reproduce the issue or help you.
Is presumptuous to ask it after? Isn't it?

**Comment by mspaulding06** [comment] 2016-07-23 19:51
Ah, sorry forgot about that.  You won't need a crystal ball ;)

Ubuntu-MATE 16.04.1 w/ systemd of course
Latest MATE 1.15 tagged code (built all debs myself)
mate-power-manager 1.15.0

**Comment by mspaulding06** [comment] 2016-07-23 20:08
Also noticed that here the state of the battery is shown as "discharging".
![screenshot at 2016-07-23 13-06-59](https://cloud.githubusercontent.com/assets/216318/17080028/7acce014-50d6-11e6-852c-28f215cc3b0a.png)

**Comment by mspaulding06** [comment] 2016-07-24 01:00
So running `upower -d` is showing that the battery is discharging as well.  I don't think this is a problem with MATE after all.  UPower is just reporting the wrong information.

**Comment by raveit65** [comment] 2016-07-24 08:44
I think nowadays upower communicate directly with systemd, and m-p-m reads it from systemd, not 100% sure.
But if upower shows the wrong information than m-p-m shows the same.
It can be also a kernel (driver) problem with your battery. And unfortunately systemd is not like systemd. Every distro use another version.
I'm using fedora 24 and i can't reproduce the wrong infos with my MSI FX700 notebook.
And i did a lot of testing the last week because of a pull request.

**Comment by monsta** [comment] 2017-10-08 13:03
Closing since it's an issue in upower or elsewhere.

**Closed by monsta** 2017-10-08 13:03 UTC
